### ISSUE TITLE
Increase font size?

### ISSUE THREAD

**Issue by Wh1t3Rose** [lucxsm/assettoserver-lua-scripts#1]
How would I increase the font size for this? It's pretty small and hard to read when driving

**Comment by Wh1t3Rose** [comment]
Posted in wrong project. Sorry.

**Comment by n0tluc** [comment]
`ui.beginTransparentWindow("overtakeScore", vec2(100, 100), vec2(400 * 0.5, 400 * 0.5))`

To change the size of the UI, you need to modify the dimensions provided in the vec2 constructor.
